import Head from 'next/head'
import styles from '@/styles/Login.module.css'
import { LoginForm } from '@/components/LoginForm'
import path from 'path'
import { api_prefix } from '@/config'

type Props = ReturnType<typeof getStaticProps>['props'];

export function getStaticProps() {
  return {
    props:{
      api_endpoint: path.join(api_prefix, 'login')
    }
  }
}

export default function Login({api_endpoint}:Props) {


  return (
    <>
      <Head>
        <title>NewtNet | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <LoginForm
         api_endpoint={api_endpoint}
         callback={(data) => console.log(data)}
         ></LoginForm>
      </main>
    </>
  )
}
