import Head from 'next/head'
import styles from '@/styles/Login.module.css'
import { LoginForm } from '@/components/LoginForm'
import path from 'path'
import { api_prefix } from '@/config'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import { LoginGet200Response } from '@/lib/api_client'
import { readCookie } from '@/lib/cookie'

type Props = ReturnType<typeof getStaticProps>['props'];

export function getStaticProps() {
  return {
    props: {
      api_endpoint: path.join(api_prefix, 'login')
    }
  }
}

export default function Login({ api_endpoint }: Props) {

  const router = useRouter();

  useEffect(() => {
    if (!router.isReady) return;

    const token = readCookie('newt_user')

    console.log(token);
    

    if (token) {
      router.push('/');
      return;
    };

  }, [router]);

  function onLogin(token:LoginGet200Response){
    router.push('/')
  }

  return (
    <>
      <Head>
        <title>NewtNet | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <LoginForm
          api_endpoint={api_endpoint}
          onLogin={onLogin}
        ></LoginForm>
      </main>
    </>
  )
}
